language: node_js
node_js:
  - "node"
install: npm install
script: npm run build
deploy:
  provider: pages
  local_dir: site
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: ghpages
