language: node_js
node_js:
  - "node"
install: npm install
script: npm run build
deploy:
  provider: pages
  local_dir: site
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    # This is the branch to WATCH, not the branch to PUSH TO.
    # Travis will push to gh-pages (implied by pages) and watch
    # master for commits.
    branch: master
