module.exports = {
  ALREADY_PERFORMED: {code: 'ALREADY_PERFORMED', message: 'This has already been done.'},
  ALREADY_PERFORMED_give_role: {code: 'ALREADY_PERFORMED', message: 'The user already has this role.'},
  ALREADY_PERFORMED_take_role: {code: 'ALREADY_PERFORMED', message: 'The user does not have this role.'},
  ALREADY_PERFORMED_pin_message: {code: 'ALREADY_PERFORMED', message: 'This message is already pinned.'},
  INCOMPLETE_PARAMETERS: {code: 'INCOMPLETE_PARAMETERS', message: 'The request is missing a parameter.'},
  INCORRECT_PASSWORD: {code: 'INCORRECT_PASSWORD', message: 'That is not the correct password.'},
  INTERNAL_ERROR: {code: 'INTERNAL_ERROR', message: 'There was an internal error.'},
  INVALID_NAME: {code: 'INVALID_NAME', message: 'That name is not valid.'},
  INVALID_PARAMETER_TYPE: {code: 'INVALID_PARAMETER_TYPE', message: 'A parameter is not of the correct type.'},
  INVALID_SESSION_ID: {code: 'INVALID_SESSION_ID', message: 'The session ID is invalid.'},
  NAME_ALREADY_TAKEN: {code: 'NAME_ALREADY_TAKEN', message: 'That name is already taken.'},
  NOT_ALLOWED: {code: 'NOT_ALLOWED', message: 'You are not allowed to do this.'},
  NOT_ALLOWED_missing_perms_of_role: {code: 'NOT_ALLOWED', message: 'You are not allowed to do this because you don\'t have one of the permissions the role specifies.'},
  NOT_ALLOWED_reorder_roles_above_self: {code: 'NOT_ALLOWED', message: 'You are not allowed to reorder roles that are higher in the existing list than your own highest-priority role.'},
  NOT_DELETABLE_ROLE: {code: 'NOT_DELETABLE_ROLE', message: 'This role is internal and cannot be deleted.'},
  NOT_FOUND: {code: 'NOT_FOUND', message: 'This couldn\'t be found.'},
  NOT_FOUND_channel: {code: 'NOT_FOUND', message: 'This channel couldn\'t be found.'},
  NOT_FOUND_emote: {code: 'NOT_FOUND', message: 'This emote couldn\'t be found.'},
  NOT_FOUND_message: {code: 'NOT_FOUND', message: 'This message couldn\'t be found.'},
  NOT_FOUND_role: {code: 'NOT_FOUND', message: 'This role couldn\'t be found.'},
  NOT_FOUND_session: {code: 'NOT_FOUND', message: 'This session couldn\'t be found.'},
  NOT_FOUND_user: {code: 'NOT_FOUND', message: 'This user couldn\'t be found.'},
  NOT_FROM_SAME_CHANNEL: {code: 'NOT_FROM_SAME_CHANNEL', message: 'This is not from the same channel.'},
  NOT_GUEST_PERMISSION: {code: 'NOT_GUEST_PERMISSION', message: 'You cannot set this permission on guest/everyone roles.'},
  NOT_YOURS: {code: 'NOT_YOURS', message: 'You don\'t own this.'},
  SHORT_PASSWORD: {code: 'SHORT_PASSWORD', message: 'Your password must be at least six characters long.'},
  UPLOAD_FAILED: {code: 'UPLOAD_FAILED', message: 'The upload failed.'},
  UPLOADS_DISABLED: {code: 'UPLOADS_DISABLED', message: 'Uploads are disabled.'},
}
