module.exports = {
  ALREADY_PERFORMED: {code: 'ALREADY_PERFORMED', message: 'You have already done this.'},
  AUTHORIZATION_ERROR: {code: 'AUTHORIZATION_ERROR', message: 'Authorization-related error.'},
  INCOMPLETE_PARAMETERS: {code: 'INCOMPLETE_PARAMETERS', message: 'The request is missing a parameter.'},
  INCORRECT_PASSWORD: {code: 'INCORRECT_PASSWORD', message: 'That is not the correct password.'},
  INTERNAL_ERROR: {code: 'INTERNAL_ERROR', message: 'There was an internal error.'},
  INVALID_NAME: {code: 'INVALID_NAME', message: 'That name is not valid.'},
  INVALID_PARAMETER_TYPE: {code: 'INVALID_PARAMETER_TYPE', message: 'A parameter is not of the correct type.'},
  INVALID_SESSION_ID: {code: 'INVALID_SESSION_ID', message: 'The session ID is invalid.'},
  MUST_BE_ADMIN: {code: 'MUST_BE_ADMIN', message: 'You must be an administrator to do this.'},
  NAME_ALREADY_TAKEN: {code: 'NAME_ALREADY_TAKEN', message: 'That name is already taken.'},
  NOT_FOUND: {code: 'NOT_FOUND', message: 'This couldn\'t be found.'},
  NOT_YOURS: {code: 'NOT_YOURS', message: 'You don\'t own this.'},
  UPLOAD_FAILED: {code: 'UPLOAD_FAILED', message: 'The upload failed.'},
  UPLOADS_DISABLED: {code: 'UPLOADS_DISABLED', message: 'Uploads are disabled.'},
}
