module.exports = {
  ALREADY_PERFORMED: {code: 'ALREADY_PERFORMED', message: 'You have already done this.'},
  INCOMPLETE_PARAMETERS: {code: 'INCOMPLETE_PARAMETERS', message: 'The request is missing a parameter.'},
  INCORRECT_PASSWORD: {code: 'INCORRECT_PASSWORD', message: 'That is not the correct password.'},
  INTERNAL_ERROR: {code: 'INTERNAL_ERROR', message: 'There was an internal error.'},
  INVALID_NAME: {code: 'INVALID_NAME', message: 'That name is not valid.'},
  INVALID_PARAMETER_TYPE: {code: 'INVALID_PARAMETER_TYPE', message: 'A parameter is not of the correct type.'},
  INVALID_SESSION_ID: {code: 'INVALID_SESSION_ID', message: 'The session ID is invalid.'},
  MISSING_PERMISSION: {code: 'MISSING_PERMISSION', message: 'You are missing a required permission.'},
  NAME_ALREADY_TAKEN: {code: 'NAME_ALREADY_TAKEN', message: 'That name is already taken.'},
  NOT_DELETABLE_ROLE: {code: 'NOT_DELETABLE_ROLE', message: 'This role is internal and cannot be deleted.'},
  NOT_FOUND: {code: 'NOT_FOUND', message: 'This couldn\'t be found.'},
  NOT_FROM_SAME_CHANNEL: {code: 'NOT_FROM_SAME_CHANNEL', message: 'This is not from the same channel.'},
  NOT_GUEST_PERMISSION: {code: 'NOT_GUEST_PERMISSION', message: 'You cannot set this permission on guest/everyone roles.'},
  NOT_YOURS: {code: 'NOT_YOURS', message: 'You don\'t own this.'},
  SHORT_PASSWORD: {code: 'SHORT_PASSWORD', message: 'Your password must be at least six characters long.'},
  UPLOAD_FAILED: {code: 'UPLOAD_FAILED', message: 'The upload failed.'},
  UPLOADS_DISABLED: {code: 'UPLOADS_DISABLED', message: 'Uploads are disabled.'},
}
